# Deploy a kustomize package that just uses the local bases from the same Git repository
# without using pipeline.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    kustomizeVersion: 3.5.5
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 100%
          createService: true
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
